### ISSUE TITLE
Python 2.7.3 AttributeError: 'NoneType' object has no attribute 'do_handshake'

### ISSUE THREAD

**Issue by entr0pist** [pycepa/pycepa#21]
```
[root@i.broke.science:~/pycepa]# ./tor.py start
2015-08-24 00:14:22,209:core.daemon: starting server..
2015-08-24 00:14:22,215:core.events: registering 'module_loaded_Select' in /root/pycepa/core/module_driver.py:54:load_module
2015-08-24 00:14:22,215:core.events: registering 'module_loaded_HTTPClient' in /root/pycepa/core/module_driver.py:56:load_module
2015-08-24 00:14:22,216:core.events: registering 'module_loaded_HTTPClient' in /root/pycepa/core/module_driver.py:54:load_module
2015-08-24 00:14:22,216:core.events: registering 'module_loaded_Tor' in /root/pycepa/core/module_driver.py:56:load_module
2015-08-24 00:14:22,216:core.events: registering 'booted' in /root/pycepa/modules/Select.py:21:module_load
2015-08-24 00:14:22,216:core.events: registering 'quit' in /root/pycepa/modules/Select.py:22:module_load
2015-08-24 00:14:22,217:core.events: registering 'fd_readable' in /root/pycepa/modules/Select.py:23:module_load
2015-08-24 00:14:22,217:core.events: registering 'fd_unreadable' in /root/pycepa/modules/Select.py:24:module_load
2015-08-24 00:14:22,217:core.events: registering 'fd_writable' in /root/pycepa/modules/Select.py:25:module_load
2015-08-24 00:14:22,217:core.events: registering 'fd_unwritable' in /root/pycepa/modules/Select.py:26:module_load
2015-08-24 00:14:22,217:core.events: registering 'fd_exceptional' in /root/pycepa/modules/Select.py:27:module_load
2015-08-24 00:14:22,217:core.events: registering 'fd_unexceptional' in /root/pycepa/modules/Select.py:28:module_load
2015-08-24 00:14:22,218:core.events: raising 'module_loaded_Select' in /root/pycepa/core/module_driver.py:55:load_module
2015-08-24 00:14:22,218:core.events: registering 'http_get' in /root/pycepa/modules/HTTPClient.py:219:module_load
2015-08-24 00:14:22,218:core.events: raising 'module_loaded_HTTPClient' in /root/pycepa/core/module_driver.py:55:load_module
2015-08-24 00:14:22,218:modules.Tor: initializing Tor.
2015-08-24 00:14:22,899:core.events: registering 'tor_init_directory_stream' in /root/pycepa/modules/Tor/Proxy.py:448:module_load
2015-08-24 00:14:22,900:core.events: raising 'module_loaded_Proxy' in /root/pycepa/core/module_driver.py:55:load_module
2015-08-24 00:14:22,900:core.events: registering 'module_loaded_Tor.Proxy' in /root/pycepa/core/module_driver.py:56:load_module
2015-08-24 00:14:22,900:core.events: registering 'tor_get_router' in /root/pycepa/modules/Tor/DirServ.py:45:module_load
2015-08-24 00:14:22,901:core.events: raising 'module_loaded_DirServ' in /root/pycepa/core/module_driver.py:55:load_module
2015-08-24 00:14:22,901:core.events: registering 'module_loaded_Tor.DirServ' in /root/pycepa/core/module_driver.py:56:load_module
2015-08-24 00:14:22,901:core.events: registering 'tor_got_md_['Guard', 'Stable', 'Fast', 'Valid', 'Running']' in /root/pycepa/modules/Tor/__init__.py:27:module_load
2015-08-24 00:14:22,901:core.events: raising 'tor_get_router' in /root/pycepa/modules/Tor/__init__.py:28:module_load
2015-08-24 00:14:22,901:modules.Tor.DirServ: requesting status-vote/current/consensus from 86.59.21.38
2015-08-24 00:14:22,902:core.events: raising 'http_get' in /root/pycepa/modules/Tor/DirServ.py:126:do_http
2015-08-24 00:14:22,902:core.events: registering 'module_loaded_Tor.Proxy' in /root/pycepa/modules/Tor/TorSocket.py:24:__init__
2015-08-24 00:14:22,903:core.events: registering 'tor_directory_stream_59433_recv' in /root/pycepa/modules/Tor/TorSocket.py:27:__init__
2015-08-24 00:14:22,903:core.events: registering 'tor_directory_stream_59433_connected' in /root/pycepa/modules/Tor/TorSocket.py:29:__init__
2015-08-24 00:14:22,903:core.events: registering 'tor_directory_stream_59433_closed' in /root/pycepa/modules/Tor/TorSocket.py:30:__init__
2015-08-24 00:14:22,903:core.events: registering 'send' in /root/pycepa/modules/Tor/TorSocket.py:31:__init__
2015-08-24 00:14:22,904:core.events: raising 'tor_init_directory_stream' in /root/pycepa/modules/Tor/TorSocket.py:64:connect
2015-08-24 00:14:22,904:core.events: registering 'send' in /root/pycepa/core/TCPClient.py:28:__init__
2015-08-24 00:14:22,905:core.events: registering 'close' in /root/pycepa/core/TCPClient.py:29:__init__
2015-08-24 00:14:22,905:core.events: registering 'connect' in /root/pycepa/core/TCPClient.py:30:__init__
2015-08-24 00:14:22,905:core.events: registering 'setup' in /root/pycepa/core/TLSClient.py:21:__init__
2015-08-24 00:14:22,906:core.events: registering 'connected' in /root/pycepa/core/TLSClient.py:22:__init__
2015-08-24 00:14:22,906:modules.Tor.Proxy: initiating connection to guard node.
2015-08-24 00:14:22,906:core.events: registering 'handshook' in /root/pycepa/modules/Tor/Proxy.py:299:__init__
2015-08-24 00:14:22,906:core.events: registering 'received' in /root/pycepa/modules/Tor/Proxy.py:300:__init__
2015-08-24 00:14:22,907:core.events: registering 'send_cell' in /root/pycepa/modules/Tor/Proxy.py:301:__init__
2015-08-24 00:14:22,907:core.events: registering '0_got_cell_Versions' in /root/pycepa/modules/Tor/Proxy.py:302:__init__
2015-08-24 00:14:22,907:core.events: registering '0_got_cell_Certs' in /root/pycepa/modules/Tor/Proxy.py:303:__init__
2015-08-24 00:14:22,907:core.events: registering '0_got_cell_AuthChallenge' in /root/pycepa/modules/Tor/Proxy.py:304:__init__
2015-08-24 00:14:22,908:core.events: registering '0_got_cell_Netinfo' in /root/pycepa/modules/Tor/Proxy.py:305:__init__
2015-08-24 00:14:22,908:core.events: registering 'tor_tor26_init_directory_stream' in /root/pycepa/modules/Tor/Proxy.py:307:__init__
2015-08-24 00:14:22,908:core.events: raising 'setup' in /root/pycepa/core/TCPClient.py:120:init
2015-08-24 00:14:22,909:core.TLSClient: Using SSL context: <module 'ssl' from '/usr/lib/python2.7/ssl.pyc'>
2015-08-24 00:14:22,909:core.events: registering 'fd_<ssl.SSLSocket object at 0x2b635f0>_readable' in /root/pycepa/core/TCPClient.py:131:init
2015-08-24 00:14:22,910:core.events: registering 'fd_<ssl.SSLSocket object at 0x2b635f0>_writable' in /root/pycepa/core/TCPClient.py:132:init
2015-08-24 00:14:22,910:core.events: registering 'fd_<ssl.SSLSocket object at 0x2b635f0>_exceptional' in /root/pycepa/core/TCPClient.py:133:init
2015-08-24 00:14:22,910:core.events: raising 'fd_writable' in /root/pycepa/core/TCPClient.py:135:init
2015-08-24 00:14:22,911:core.events: raising 'fd_exceptional' in /root/pycepa/core/TCPClient.py:136:init
2015-08-24 00:14:22,911:core.events: raising 'init' in /root/pycepa/core/TCPClient.py:138:init
2015-08-24 00:14:22,911:core.events: registering 'tor_tor26_proxy_initialized' in /root/pycepa/modules/Tor/Proxy.py:468:init_directory_stream
2015-08-24 00:14:22,912:core.events: registering 'received' in /root/pycepa/modules/Tor/TorLineClient.py:17:__init__
2015-08-24 00:14:22,912:core.events: registering 'closed' in /root/pycepa/modules/Tor/TorLineClient.py:18:__init__
2015-08-24 00:14:22,912:core.events: registering 'connected' in /root/pycepa/modules/HTTPClient.py:41:__init__
2015-08-24 00:14:22,912:core.events: registering 'line' in /root/pycepa/modules/HTTPClient.py:42:__init__
2015-08-24 00:14:22,913:core.events: registering 'chunk' in /root/pycepa/modules/HTTPClient.py:43:__init__
2015-08-24 00:14:22,913:core.events: registering 'line_closed' in /root/pycepa/modules/HTTPClient.py:44:__init__
2015-08-24 00:14:22,913:core.events: registering 'chunk' in /root/pycepa/modules/Tor/DirServ.py:127:do_http
2015-08-24 00:14:22,913:core.events: registering 'done' in /root/pycepa/modules/Tor/DirServ.py:128:do_http
2015-08-24 00:14:22,913:core.events: raising 'module_loaded_Tor' in /root/pycepa/core/module_driver.py:55:load_module
2015-08-24 00:14:22,914:core.events: registering 'module_loaded_Select' in /root/pycepa/core/module_driver.py:56:load_module
2015-08-24 00:14:22,914:core.daemon: server successfully started.
2015-08-24 00:14:22,914:core.events: raising 'booted' in /root/pycepa/core/daemon.py:85:start
2015-08-24 00:14:22,939:core.events: raising 'fd_<ssl.SSLSocket object at 0x2b635f0>_writable' in /root/pycepa/modules/Select.py:60:booted
2015-08-24 00:14:22,940:core.events: raising 'fd_unwritable' in /root/pycepa/core/TCPClient.py:66:writable
2015-08-24 00:14:22,940:core.events: raising 'fd_readable' in /root/pycepa/core/TCPClient.py:67:writable
2015-08-24 00:14:22,940:core.events: raising 'connected' in /root/pycepa/core/TCPClient.py:68:writable
Traceback (most recent call last):
  File "./tor.py", line 18, in <module>
    getattr(daemon, sys.argv[1])(daemon=False)
  File "/root/pycepa/core/daemon.py", line 85, in start
    events.trigger('booted')
  File "/root/pycepa/core/events.py", line 107, in trigger
    ret = function(*args, **kwargs)
  File "/root/pycepa/modules/Select.py", line 60, in booted
    self.trigger(event_strings[e] % fd, fd)
  File "/root/pycepa/core/Module.py", line 116, in trigger
    return self.events.trigger(event, *args, **kwargs)
  File "/root/pycepa/core/events.py", line 107, in trigger
    ret = function(*args, **kwargs)
  File "/root/pycepa/core/TCPClient.py", line 68, in writable
    self.trigger_local('connected')
  File "/root/pycepa/core/LocalModule.py", line 44, in trigger_local
    return self._events.trigger(event, *args, **kwargs)
  File "/root/pycepa/core/events.py", line 107, in trigger
    ret = function(*args, **kwargs)
  File "/root/pycepa/core/TLSClient.py", line 69, in do_handshake
    self.sock.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
AttributeError: 'NoneType' object has no attribute 'do_handshake'
[root@i.broke.science:~/pycepa]# 
```

**Comment by entr0pist** [comment]
Confirmed that this affects the newest version of pycepa:

```
[root@i.broke.science:~/pycepa]# ./tor.py start
2015-09-19 05:02:39,014:core.daemon: starting server..
2015-09-19 05:02:39,023:modules.Tor: initializing Tor.
2015-09-19 05:02:40,339:modules.Test: requesting http://google.com/
2015-09-19 05:02:40,344:modules.Tor.TorConnection: initiating connection to guard node SoulOfTheInternet: 109.239.48.152:6666.
2015-09-19 05:02:40,351:core.daemon: server successfully started.
Traceback (most recent call last):
  File "./tor.py", line 18, in <module>
    getattr(daemon, sys.argv[1])(daemon=False)
  File "/root/pycepa/core/daemon.py", line 85, in start
    events.trigger('booted')
  File "/root/pycepa/core/events.py", line 107, in trigger
    ret = function(*args, **kwargs)
  File "/root/pycepa/modules/Select.py", line 60, in booted
    self.trigger(event_strings[e] % fd, fd)
  File "/root/pycepa/core/Module.py", line 116, in trigger
    return self.events.trigger(event, *args, **kwargs)
  File "/root/pycepa/core/events.py", line 107, in trigger
    ret = function(*args, **kwargs)
  File "/root/pycepa/core/TCPClient.py", line 68, in writable
    self.trigger_local('connected')
  File "/root/pycepa/core/LocalModule.py", line 44, in trigger_local
    return self._events.trigger(event, *args, **kwargs)
  File "/root/pycepa/core/events.py", line 107, in trigger
    ret = function(*args, **kwargs)
  File "/root/pycepa/core/TLSClient.py", line 69, in do_handshake
    self.sock.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
AttributeError: 'NoneType' object has no attribute 'do_handshake'
[root@i.broke.science:~/pycepa]# 
```

**Comment by entr0pist** [comment]
Confirmed:

```
[root@i.broke.science:~/pycepa]# ./tor.py start
2015-09-19 05:27:55,458:core.daemon: starting server..
2015-09-19 05:27:55,490:modules.Tor: initializing Tor.
2015-09-19 05:27:57,359:modules.Test: requesting http://google.com/
2015-09-19 05:27:57,368:modules.Tor.TorConnection: initiating connection to guard node SoulOfTheInternet: 109.239.48.152:6666.
2015-09-19 05:27:57,375:core.daemon: server successfully started.
2015-09-19 05:27:57,499:modules.Tor.TorConnection: connection to guard node established.
```
