### ISSUE TITLE
Windows: select.poll() does not exist

### ISSUE THREAD

**Issue by 0x27** [pycepa/pycepa#22]
Did a quick test on Windows, tl;dr, select on Windows has no "poll" method.

Going to need to work around this somehow for cross platform usability...

**Comment by entr0pist** [comment]
@0x27 does that fix it? :)

**Comment by 0x27** [comment]
Will test later today and report back :)

**Comment by 0x27** [comment]
gdi. Still not working.

```
C:\Users\infodox\Downloads\pycepa-master\pycepa-master>ver

Microsoft Windows [Version 6.1.7601]

C:\Users\infodox\Downloads\pycepa-master\pycepa-master>python -V
Python 2.7.10

C:\Users\infodox\Downloads\pycepa-master\pycepa-master>python tor.py start
2015-09-19 21:31:16,105:core.daemon: starting server..
2015-09-19 21:31:16,119:modules.Tor: initializing Tor.
2015-09-19 21:31:16,401:modules.Test: requesting http://google.com/
2015-09-19 21:31:16,854:modules.Tor.TorConnection: initiating connection to guar
d node SoulOfTheInternet: 109.239.48.152:6666.
2015-09-19 21:31:16,854:core.daemon: server boot failed: 'module' object has no
attribute 'POLLIN'
Traceback (most recent call last):
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\daemon.py",
line 64, in start
    modules.load_all()
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\module_drive
r.py", line 36, in load_all
    self.load_module(module_name)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\module_drive
r.py", line 56, in load_module
    self.pending_modules[module_name].init_module()
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\Module.py",
line 65, in init_module
    self.trigger('module_loaded_%s' % name, name)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\Module.py",
line 116, in trigger
    return self.events.trigger(event, *args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\events.py",
line 107, in trigger
    ret = function(*args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\Module.py",
line 48, in dependency_loaded
    self.init_module()
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\Module.py",
line 63, in init_module
    self.module_load()
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\modules\Test.py",
 line 21, in module_load
    request = self.trigger('http_get', 'http://74.125.136.101/')
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\Module.py",
line 116, in trigger
    return self.events.trigger(event, *args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\events.py",
line 107, in trigger
    ret = function(*args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\modules\HTTPClien
t.py", line 232, in get
    request = HTTPRequest(url, headers=headers, directory=directory)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\modules\HTTPClien
t.py", line 43, in __init__
    super(HTTPRequest, self).__init__((self.url.hostname, self.port), directory)

  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\modules\Tor\TorLi
neClient.py", line 15, in __init__
    super(TorLineClient, self).__init__(host=host, directory=directory)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\modules\Tor\TorSo
cket.py", line 36, in __init__
    self.connect()
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\modules\Tor\TorSo
cket.py", line 93, in connect
    self.trigger_avail('tor_init_stream', self.stream_id)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\Module.py",
line 122, in trigger_avail
    return self.events.trigger_avail(event, *args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\events.py",
line 90, in trigger_avail
    self.trigger(event, *args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\events.py",
line 107, in trigger
    ret = function(*args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\modules\Tor\Proxy
.py", line 34, in get_stream
    TorConnection(circuit[0])
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\modules\Tor\TorCo
nnection.py", line 68, in __init__
    self.init()
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\TCPClient.py
", line 124, in init
    self.die()
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\TCPClient.py
", line 162, in die
    self.trigger('fd_unreadable', self.sock)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\Module.py",
line 116, in trigger
    return self.events.trigger(event, *args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\core\events.py",
line 107, in trigger
    ret = function(*args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\pycepa-master\modules\Select.py
", line 161, in fd_unreadable
    self.init_fd(fd, select.POLLIN, add=False)
AttributeError: 'module' object has no attribute 'POLLIN'

C:\Users\infodox\Downloads\pycepa-master\pycepa-master>
```

**Comment by entr0pist** [comment]
Okay, I added those. That should do it.

**Comment by 0x27** [comment]
Will retest shortly :)

**Comment by 0x27** [comment]
Well, we now have another select issue it appears... Is it just me or is select completely screwed on Windows?

```
C:\Users\infodox\Downloads\pycepa-master>python tor.py start
2015-09-19 23:36:39,553:core.daemon: starting server..
2015-09-19 23:36:39,584:modules.Tor: initializing Tor.
2015-09-19 23:36:40,134:modules.Test: requesting http://google.com/
2015-09-19 23:36:40,944:modules.Tor.TorConnection: initiating connection to guar
d node SoulOfTheInternet: 109.239.48.152:6666.
2015-09-19 23:36:40,963:core.daemon: server successfully started.
Traceback (most recent call last):
  File "tor.py", line 18, in <module>
    getattr(daemon, sys.argv[1])(daemon=False)
  File "C:\Users\infodox\Downloads\pycepa-master\core\daemon.py", line 85, in st
art
    events.trigger('booted')
  File "C:\Users\infodox\Downloads\pycepa-master\core\events.py", line 107, in t
rigger
    ret = function(*args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\modules\Select.py", line 107, i
n booted
    events = self.poll.poll()
  File "C:\Users\infodox\Downloads\pycepa-master\modules\Select.py", line 16, in
 poll
    r, w, x = select.select(self.readable(), self.writable(), self.exceptional()
)
select.error: (10022, 'An invalid argument was supplied')

C:\Users\infodox\Downloads\pycepa-master>
```

Debug Output:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\infodox>cd Downloads\pycepa-master

C:\Users\infodox\Downloads\pycepa-master>python tor.py start
2015-09-19 23:40:41,407:core.daemon: starting server..
2015-09-19 23:40:41,417:core.events: registering 'module_loaded_Select' in C:\Us
ers\infodox\Downloads\pycepa-master\core\module_driver.py:54:load_module
2015-09-19 23:40:41,417:core.events: registering 'module_loaded_HTTPClient' in C
:\Users\infodox\Downloads\pycepa-master\core\module_driver.py:55:load_module
2015-09-19 23:40:41,417:core.events: registering 'module_loaded_Select' in C:\Us
ers\infodox\Downloads\pycepa-master\core\module_driver.py:55:load_module
2015-09-19 23:40:41,417:core.events: registering 'booted' in C:\Users\infodox\Do
wnloads\pycepa-master\modules\Select.py:81:module_load
2015-09-19 23:40:41,417:core.events: registering 'quit' in C:\Users\infodox\Down
loads\pycepa-master\modules\Select.py:82:module_load
2015-09-19 23:40:41,417:core.events: registering 'fd_readable' in C:\Users\infod
ox\Downloads\pycepa-master\modules\Select.py:83:module_load
2015-09-19 23:40:41,417:core.events: registering 'fd_unreadable' in C:\Users\inf
odox\Downloads\pycepa-master\modules\Select.py:84:module_load
2015-09-19 23:40:41,427:core.events: registering 'fd_writable' in C:\Users\infod
ox\Downloads\pycepa-master\modules\Select.py:85:module_load
2015-09-19 23:40:41,427:core.events: registering 'fd_unwritable' in C:\Users\inf
odox\Downloads\pycepa-master\modules\Select.py:86:module_load
2015-09-19 23:40:41,427:core.events: registering 'fd_exceptional' in C:\Users\in
fodox\Downloads\pycepa-master\modules\Select.py:87:module_load
2015-09-19 23:40:41,427:core.events: registering 'fd_unexceptional' in C:\Users\
infodox\Downloads\pycepa-master\modules\Select.py:88:module_load
2015-09-19 23:40:41,427:core.events: raising 'module_loaded_Select' in C:\Users\
infodox\Downloads\pycepa-master\core\module_driver.py:56:load_module
2015-09-19 23:40:41,427:core.events: registering 'http_get' in C:\Users\infodox\
Downloads\pycepa-master\modules\HTTPClient.py:226:module_load
2015-09-19 23:40:41,427:core.events: raising 'module_loaded_HTTPClient' in C:\Us
ers\infodox\Downloads\pycepa-master\core\module_driver.py:56:load_module
2015-09-19 23:40:41,427:core.events: registering 'module_loaded_Tor' in C:\Users
\infodox\Downloads\pycepa-master\core\module_driver.py:54:load_module
2015-09-19 23:40:41,427:core.events: registering 'module_loaded_Test' in C:\User
s\infodox\Downloads\pycepa-master\core\module_driver.py:55:load_module
2015-09-19 23:40:41,427:core.events: registering 'module_loaded_Tor' in C:\Users
\infodox\Downloads\pycepa-master\core\module_driver.py:55:load_module
2015-09-19 23:40:41,427:modules.Tor: initializing Tor.
2015-09-19 23:40:41,726:core.events: registering 'module_loaded_Tor.Proxy' in C:
\Users\infodox\Downloads\pycepa-master\core\module_driver.py:55:load_module
2015-09-19 23:40:41,726:core.events: registering 'tor_init_stream' in C:\Users\i
nfodox\Downloads\pycepa-master\modules\Tor\Proxy.py:18:module_load
2015-09-19 23:40:41,726:core.events: raising 'module_loaded_Proxy' in C:\Users\i
nfodox\Downloads\pycepa-master\core\module_driver.py:56:load_module
2015-09-19 23:40:41,726:core.events: registering 'module_loaded_Tor.DirServ' in
C:\Users\infodox\Downloads\pycepa-master\core\module_driver.py:55:load_module
2015-09-19 23:40:41,726:core.events: registering 'tor_get_router' in C:\Users\in
fodox\Downloads\pycepa-master\modules\Tor\DirServ.py:56:module_load
2015-09-19 23:40:41,726:core.events: registering 'tor_parsed_router' in C:\Users
\infodox\Downloads\pycepa-master\modules\Tor\DirServ.py:57:module_load
2015-09-19 23:40:41,726:core.events: registering 'tor_parsed_md' in C:\Users\inf
odox\Downloads\pycepa-master\modules\Tor\DirServ.py:58:module_load
2015-09-19 23:40:41,726:core.events: raising 'module_loaded_DirServ' in C:\Users
\infodox\Downloads\pycepa-master\core\module_driver.py:56:load_module
2015-09-19 23:40:41,726:core.events: registering 'tor_got_md_['Guard', 'Stable',
 'Fast', 'Valid', 'Running']' in C:\Users\infodox\Downloads\pycepa-master\module
s\Tor\__init__.py:25:module_load
2015-09-19 23:40:41,726:core.events: raising 'module_loaded_Tor' in C:\Users\inf
odox\Downloads\pycepa-master\core\module_driver.py:56:load_module
2015-09-19 23:40:41,726:modules.Test: requesting http://google.com/
2015-09-19 23:40:41,736:core.events: raising 'http_get' in C:\Users\infodox\Down
loads\pycepa-master\modules\Test.py:21:module_load
2015-09-19 23:40:41,736:core.events: registering 'module_loaded_Tor.Proxy' in C:
\Users\infodox\Downloads\pycepa-master\modules\Tor\TorSocket.py:23:__init__
2015-09-19 23:40:41,736:core.events: registering 'tor_stream_47745_initialized'
in C:\Users\infodox\Downloads\pycepa-master\modules\Tor\TorSocket.py:29:__init__

2015-09-19 23:40:41,736:core.events: registering 'tor_stream_47745_connected' in
 C:\Users\infodox\Downloads\pycepa-master\modules\Tor\TorSocket.py:30:__init__
2015-09-19 23:40:41,736:core.events: registering 'tor_stream_47745_recv' in C:\U
sers\infodox\Downloads\pycepa-master\modules\Tor\TorSocket.py:31:__init__
2015-09-19 23:40:41,736:core.events: registering 'tor_stream_47745_closed' in C:
\Users\infodox\Downloads\pycepa-master\modules\Tor\TorSocket.py:32:__init__
2015-09-19 23:40:41,736:core.events: registering 'send' in C:\Users\infodox\Down
loads\pycepa-master\modules\Tor\TorSocket.py:33:__init__
2015-09-19 23:40:41,736:core.events: raising 'tor_init_stream' in C:\Users\infod
ox\Downloads\pycepa-master\modules\Tor\TorSocket.py:93:connect
2015-09-19 23:40:41,736:core.events: registering 'tor_SoulOfTheInternet_proxy_in
itialized' in C:\Users\infodox\Downloads\pycepa-master\modules\Tor\Proxy.py:33:g
et_stream
2015-09-19 23:40:41,736:core.events: registering 'send' in C:\Users\infodox\Down
loads\pycepa-master\core\TCPClient.py:28:__init__
2015-09-19 23:40:41,736:core.events: registering 'close' in C:\Users\infodox\Dow
nloads\pycepa-master\core\TCPClient.py:29:__init__
2015-09-19 23:40:41,746:core.events: registering 'connect' in C:\Users\infodox\D
ownloads\pycepa-master\core\TCPClient.py:30:__init__
2015-09-19 23:40:41,746:core.events: registering 'setup' in C:\Users\infodox\Dow
nloads\pycepa-master\core\TLSClient.py:21:__init__
2015-09-19 23:40:41,746:core.events: registering 'connected' in C:\Users\infodox
\Downloads\pycepa-master\core\TLSClient.py:22:__init__
2015-09-19 23:40:42,207:modules.Tor.TorConnection: initiating connection to guar
d node SoulOfTheInternet: 109.239.48.152:6666.
2015-09-19 23:40:42,207:core.events: registering 'handshook' in C:\Users\infodox
\Downloads\pycepa-master\modules\Tor\TorConnection.py:59:__init__
2015-09-19 23:40:42,207:core.events: registering 'received' in C:\Users\infodox\
Downloads\pycepa-master\modules\Tor\TorConnection.py:60:__init__
2015-09-19 23:40:42,207:core.events: registering 'send_cell' in C:\Users\infodox
\Downloads\pycepa-master\modules\Tor\TorConnection.py:61:__init__
2015-09-19 23:40:42,207:core.events: registering '0_got_cell_Versions' in C:\Use
rs\infodox\Downloads\pycepa-master\modules\Tor\TorConnection.py:62:__init__
2015-09-19 23:40:42,207:core.events: registering '0_got_cell_Certs' in C:\Users\
infodox\Downloads\pycepa-master\modules\Tor\TorConnection.py:63:__init__
2015-09-19 23:40:42,207:core.events: registering '0_got_cell_AuthChallenge' in C
:\Users\infodox\Downloads\pycepa-master\modules\Tor\TorConnection.py:64:__init__

2015-09-19 23:40:42,207:core.events: registering '0_got_cell_Netinfo' in C:\User
s\infodox\Downloads\pycepa-master\modules\Tor\TorConnection.py:65:__init__
2015-09-19 23:40:42,217:core.events: registering 'tor_SoulOfTheInternet_init_str
eam' in C:\Users\infodox\Downloads\pycepa-master\modules\Tor\TorConnection.py:66
:__init__
2015-09-19 23:40:42,217:core.events: raising 'setup' in C:\Users\infodox\Downloa
ds\pycepa-master\core\TCPClient.py:120:init
2015-09-19 23:40:42,217:core.TLSClient: Using SSL context: <ssl.SSLContext objec
t at 0x0000000003BE89E8>
2015-09-19 23:40:42,217:core.events: raising 'fd_unreadable' in C:\Users\infodox
\Downloads\pycepa-master\core\TCPClient.py:162:die
2015-09-19 23:40:42,217:core.events: raising 'fd_unwritable' in C:\Users\infodox
\Downloads\pycepa-master\core\TCPClient.py:163:die
2015-09-19 23:40:42,217:core.events: raising 'fd_unexceptional' in C:\Users\info
dox\Downloads\pycepa-master\core\TCPClient.py:164:die
2015-09-19 23:40:42,217:core.events: raising 'die' in C:\Users\infodox\Downloads
\pycepa-master\core\TCPClient.py:173:die
2015-09-19 23:40:42,217:core.events: registering 'received' in C:\Users\infodox\
Downloads\pycepa-master\modules\Tor\TorLineClient.py:17:__init__
2015-09-19 23:40:42,217:core.events: registering 'closed' in C:\Users\infodox\Do
wnloads\pycepa-master\modules\Tor\TorLineClient.py:18:__init__
2015-09-19 23:40:42,217:core.events: registering 'connected' in C:\Users\infodox
\Downloads\pycepa-master\modules\HTTPClient.py:45:__init__
2015-09-19 23:40:42,226:core.events: registering 'line' in C:\Users\infodox\Down
loads\pycepa-master\modules\HTTPClient.py:46:__init__
2015-09-19 23:40:42,226:core.events: registering 'chunk' in C:\Users\infodox\Dow
nloads\pycepa-master\modules\HTTPClient.py:47:__init__
2015-09-19 23:40:42,226:core.events: registering 'line_closed' in C:\Users\infod
ox\Downloads\pycepa-master\modules\HTTPClient.py:48:__init__
2015-09-19 23:40:42,226:core.events: registering 'data' in C:\Users\infodox\Down
loads\pycepa-master\modules\Test.py:22:module_load
2015-09-19 23:40:42,226:core.events: registering 'done' in C:\Users\infodox\Down
loads\pycepa-master\modules\Test.py:23:module_load
2015-09-19 23:40:42,226:core.events: raising 'module_loaded_Test' in C:\Users\in
fodox\Downloads\pycepa-master\core\module_driver.py:56:load_module
2015-09-19 23:40:42,226:core.daemon: server successfully started.
2015-09-19 23:40:42,226:core.events: raising 'booted' in C:\Users\infodox\Downlo
ads\pycepa-master\core\daemon.py:85:start
Traceback (most recent call last):
  File "tor.py", line 18, in <module>
    getattr(daemon, sys.argv[1])(daemon=False)
  File "C:\Users\infodox\Downloads\pycepa-master\core\daemon.py", line 85, in st
art
    events.trigger('booted')
  File "C:\Users\infodox\Downloads\pycepa-master\core\events.py", line 107, in t
rigger
    ret = function(*args, **kwargs)
  File "C:\Users\infodox\Downloads\pycepa-master\modules\Select.py", line 107, i
n booted
    events = self.poll.poll()
  File "C:\Users\infodox\Downloads\pycepa-master\modules\Select.py", line 16, in
 poll
    r, w, x = select.select(self.readable(), self.writable(), self.exceptional()
)
select.error: (10022, 'An invalid argument was supplied')

C:\Users\infodox\Downloads\pycepa-master>
```

Edit: This error code seems to be due to sockets on Windows being fucking stupid: http://stackoverflow.com/questions/7103182/python-select-select-error-10022-on-windows
